// Generated by Selenium IDE
package ImportacaoSeleniumIDE;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AcessarsiteseleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void acessarsiteselenium() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(571, 914));
    driver.findElement(By.name("q")).sendKeys("selenium");
    driver.findElement(By.cssSelector(".ds:nth-child(1) .lsb")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) .j039Wc .BNeawe")).click();
    driver.findElement(By.cssSelector(".d-1:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".d-1:nth-child(1)")).getText(), is("Selenium automates browsers. That\\\'s it!"));
  }
}
